version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: eda
    container_name: eda
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
      - 5678:5678
    volumes:
      - .:/code
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: eda-redis

# Manage container
# docker compose up
# docker compose up --build -d
# docker compose stop
# docker compose down

# Rebuilder container
# docker compose build 